potion.fire_resistance=E49A3A
potion.instant_damage=430A09
potion.invisibility=7F8392
potion.jump_boost=786297
potion.luck=339900
potion.night_vision=1F1FA1
potion.poison=4E9331
potion.resistance=99453A
potion.slow_falling=FFEFD1
potion.slowness=5A6C81
potion.speed=7CAFC6
potion.strength=932423
potion.water_breathing=2E5299
potion.wither=352A27