name: Build and Optimize

on:
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Optimize and Zip with PackSquash
        uses: ComunidadAylas/PackSquash-action@v4
        with:
          packsquash_version: latest
          options: |
            pack_directory = 'resources'
            output_file_path = 'Optimized-ResourcePack.zip'

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Optimized-Resource-Pack
          path: Optimized-ResourcePack.zip
          retention-days: 7